spring:
  application:
    name: pageHelper-demo-1
  datasource:
    url: jdbc:mysql://localhost:3306/mybatisdb?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: qaz98188729

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.xumob.pagehelperdemo1.entity
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true

pagehelper:
  support-methods-arguments: true
  reasonable: true
  helper-dialect: mysql
